FROM ubuntu:18.04

LABEL maintainer="inhere <dx0w0xb@lookout.com>" version="1.0"

# --build-arg timezone=Asia/Shanghai
ARG timezone=Asia/Shanghai
# app env: prod pre test dev
ARG app_env=prod
# default use www-data user
ARG work_user=www-data




