# 需要nginx负载node的ip和端口
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    name: my-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32143