version: '3.4'
services:
  mysql-dev:
    image: mysql:5.7.32
    container_name: mysql-dev
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '13306:3306'
    volumes:
      - ./mysql_dev/conf:/etc/mysql
      - ./mysql_dev/log:/var/log/mysql
      - ./mysql_dev/data:/var/lib/mysql

  mysql-pro:
    image: mysql:5.7.32
    container_name: mysql-pro
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '23306:3306'
    volumes:
      - ./mysql_pro/conf:/etc/mysql
      - ./mysql_pro/log:/var/log/mysql
      - ./mysql_pro/data:/var/lib/mysql
