spring:
  application:
    name : springbootZuul

server:
  port : 80

eureka:
  client:
    service-url:
      defaultZone : http://192.168.2.133:5000/eureka/,http://192.168.2.199:5000/eureka/

zuul:
  routes:
    sbService :
      path : /sbService/**
      serviceId : springbootService

    OcrServer: 
      path: /OcrServer/**
      serviceId: OcrServer
