---
- hosts: nginx_app
  remote_user: root

  tasks:
    - name: add saasapi
      lineinfile:
        dest: /etc/nginx/sites-available/default
        line: "\nupstream saasapi {\n  server 192.168.2.175:80;\n  server 192.168.2.108:80;\n  fair;\n}\n\nserver {\n  listen 80;\n  server_name saasapi.atjubo.com;\n  location / {\n    proxy_store off;\n    proxy_redirect off;\n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    proxy_set_header X-Real-IP $remote_addr;\n    proxy_set_header Host $http_host;\n    proxy_pass http://saasapi;\n    client_max_body_size 5M;\n\n  }\n}\n"

    - name: add saasadmin
      lineinfile:
        dest: /etc/nginx/sites-available/default
        line: "\nupstream saasadmin {\n  server 192.168.2.175:80;\n  fair;\n}\n\nserver {\n  listen 80;\n  server_name saasadmin.atjubo.com;\n  location / {\n    proxy_store off;\n    proxy_redirect off;\n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    proxy_set_header X-Real-IP $remote_addr;\n    proxy_set_header Host $http_host;\n    proxy_pass http://saasadmin;\n    client_max_body_size 5M;\n\n  }\n}\n"

    - name: add saasoss
      lineinfile:
        dest: /etc/nginx/sites-available/default
        line: "\nupstream saasoss {\n  server 192.168.2.175:80;\n  fair;\n}\n\nserver {\n  listen 80;\n  server_name saasoss.atjubo.com;\n  location / {\n    proxy_store off;\n    proxy_redirect off;\n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    proxy_set_header X-Real-IP $remote_addr;\n    proxy_set_header Host $http_host;\n    proxy_pass http://saasoss;\n    client_max_body_size 5M;\n\n  }\n}\n"

    - name: reload nginx
      service:
        name: nginx
        state: reloaded