---
- hosts: add
  remote_user: root

  tasks:
  - name: change password
    user: name={{item.user}} password={{item.password | password_hash('sha512')}} update_password=always
    with_items:
      - {user: 'dever', password: 'server_dever_123'}
      - {user: 'root', password: 'server_root_456'}
