server:
  port: 5000


spring:
  application:
    name: springbootEureka

eureka:
  server:
        enableSelfPreservation: false
        
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.2.133:5000/eureka/,http://192.168.2.199:5000/eureka/